name: push

on: 
  pull_request:
  push:

jobs:
  build:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest   
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-dev.txt
        pip install -e .
    - name: Running pre-commit
      uses: pre-commit/action@v3.0.0
      with:
        extra_args: --all-files
    # - name: Run tests
    #   continue-on-error: true
    #   run: pytest --junitxml=pytest.xml
    # - name: Pytest coverage comment
    #   uses: MishaKav/pytest-coverage-comment@main
    #   if: github.event_name == 'pull_request'
    #   with:
    #     pytest-xml-coverage-path: ./covreport.xml
